# Generated by Django 5.1.4 on 2024-12-31 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('objetivo', models.CharField(max_length=500)),
                ('imagen', models.URLField()),
                ('semestre', models.CharField(max_length=50)),
            ],
        ),
    ]
