# Generated by Django 5.1.4 on 2025-01-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artezt0003', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='objetivo',
            field=models.TextField(max_length=500),
        ),
    ]
