# Generated by Django 5.1.4 on 2025-01-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artezt0003', '0002_alter_entrada_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('Comentario', models.TextField(max_length=500)),
            ],
        ),
    ]
