# Generated by Django 5.1.4 on 2025-01-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artezt0003', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Comentario',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='curso',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='curso',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='objetivo',
            field=models.TextField(max_length=5000),
        ),
    ]
